2020-07-10 10:05:29,717 DEBUG - (carl.dasig) - Successfully loaded and updated table
2020-07-10 11:39:25,473 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-07-10 11:41:06,034 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-07-10 14:02:44,560 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-07-10 14:27:17,331 DEBUG - (roni) - Successfully loaded and updated table
2020-07-10 14:27:19,877 DEBUG - (roni) - Successfully loaded and updated table
2020-07-10 15:01:26,300 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-07-10 15:01:36,157 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
