2020-07-16 11:57:24,125 DEBUG - (carl.dasig) - Successfully loaded and updated table
2020-07-16 13:35:51,718 DEBUG - (terrytang) - Successfully loaded and updated table
2020-07-16 13:36:06,982 DEBUG - (terrytang) - Successfully loaded and updated table
2020-07-16 15:34:53,693 DEBUG - (AnonymousUser) - Successfully loaded and updated table
2020-07-16 18:03:27,575 DEBUG - (rock.lim) - Successfully loaded and updated table
2020-07-16 20:01:37,617 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 40, in get
    context['data'] = ZABBIX.getAllEvents(daysfromnow=period)[-limit:]
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 121, in getAllEvents
    events = self.zapi.do_request('event.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
