2021-01-19 15:51:56,249 DEBUG - (alexeio) - Successfully loaded and updated table
2021-01-19 15:52:28,071 DEBUG - (alexeio) - Successfully loaded and updated table
2021-01-19 16:19:11,505 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 299-303: ordinal not in range(128)
2021-01-19 16:30:09,547 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 301-305: ordinal not in range(128)
2021-01-19 16:30:31,166 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 307-308: ordinal not in range(128)
2021-01-19 16:40:15,626 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 295-297: ordinal not in range(128)
2021-01-19 16:42:18,807 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 267-269: ordinal not in range(128)
2021-01-19 17:28:24,263 DEBUG - (rock.lim) - Successfully loaded and updated table
2021-01-19 17:28:35,358 DEBUG - (rock.lim) - Successfully loaded and updated table
2021-01-20 03:36:02,403 DEBUG - starting thread (client mode): 0xb34687d0L
2021-01-20 03:36:02,403 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-01-20 03:36:03,634 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-01-20 03:36:03,634 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-01-20 03:36:04,024 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-01-20 03:36:04,024 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-01-20 03:36:04,024 DEBUG - HostKey agreed: ssh-ed25519
2021-01-20 03:36:04,024 DEBUG - Cipher agreed: aes128-ctr
2021-01-20 03:36:04,024 DEBUG - MAC agreed: hmac-sha2-256
2021-01-20 03:36:04,025 DEBUG - Compression agreed: none
2021-01-20 03:36:04,045 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-01-20 03:36:04,046 DEBUG - Switch to new keys ...
2021-01-20 03:36:04,052 DEBUG - Adding ssh-ed25519 host key for [123.1.189.31]:28032: f0e839335cba3de5a05d8dd23be98e47
2021-01-20 03:36:04,053 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-01-20 03:36:04,087 DEBUG - userauth is OK
2021-01-20 03:36:04,194 INFO - Authentication (publickey) successful!
2021-01-20 03:36:04,220 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-01-20 03:36:04,434 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-01-20 03:36:04,435 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-01-20 03:36:04,435 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-01-20 03:36:04,435 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-01-20 03:36:04,435 DEBUG - Secsh channel 0 opened.
2021-01-20 03:36:04,446 DEBUG - [chan 0] Sesch channel 0 request ok
2021-01-20 03:36:04,456 DEBUG - [chan 0] Sesch channel 0 request ok
2021-01-20 03:36:04,456 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-01-20 03:36:04,458 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-01-20 03:36:04,458 DEBUG - Secsh channel 1 opened.
2021-01-20 03:36:04,471 DEBUG - [chan 1] Sesch channel 1 request ok
2021-01-20 03:36:14,613 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-01-20 03:36:14,615 DEBUG - [chan 1] EOF received (1)
2021-01-20 03:36:14,615 DEBUG - [chan 1] EOF sent (1)
2021-01-20 03:36:14,616 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-01-20 03:36:14,616 DEBUG - Secsh channel 2 opened.
2021-01-20 03:36:14,669 DEBUG - [chan 2] Sesch channel 2 request ok
2021-01-20 03:36:14,696 DEBUG - [chan 2] EOF received (2)
2021-01-20 03:36:14,696 DEBUG - [chan 2] EOF sent (2)
2021-01-20 03:36:14,697 DEBUG - EOF in transport thread
2021-01-20 10:09:19,203 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 297-299: ordinal not in range(128)
2021-01-20 13:43:30,332 ERROR - Internal Server Error: /fwdcontrol/test-public-nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/fwdcontrol/views.py", line 46, in get
    context['content'] = result.get()
  File "/app/argus_final/venv/lib/python2.7/site-packages/celery/result.py", line 224, in get
    on_message=on_message,
  File "/app/argus_final/venv/lib/python2.7/site-packages/celery/backends/async.py", line 190, in wait_for_pending
    return result.maybe_throw(callback=callback, propagate=propagate)
  File "/app/argus_final/venv/lib/python2.7/site-packages/celery/result.py", line 329, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/app/argus_final/venv/lib/python2.7/site-packages/celery/result.py", line 322, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/vine/promises.py", line 217, in throw
    reraise(type(exc), exc, tb)
  File "<string>", line 1, in reraise
IOError: (u'[', u'E', u'r', u'r', u'n', u'o', u' ', u'2', u'1', u']', u' ', u'I', u's', u' ', u'a', u' ', u'd', u'i', u'r', u'e', u'c', u't', u'o', u'r', u'y', u':', u' ', u'u', u"'", u'/', u's', u'r', u'v', u'/', u't', u'e', u's', u't', u'-', u'p', u'u', u'b', u'l', u'i', u'c', u'-', u'n', u'g', u'i', u'n', u'x', u'/', u'c', u'o', u'n', u'f', u'.', u'd', u'/', u'l', u'e', u't', u's', u'e', u'n', u'c', u'r', u'y', u'p', u't', u'-', u's', u's', u'l', u"'")
2021-01-20 14:44:39,030 DEBUG - starting thread (client mode): 0xb322cbd0L
2021-01-20 14:44:39,031 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-01-20 14:44:39,058 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-01-20 14:44:39,059 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-01-20 14:44:39,078 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-01-20 14:44:39,079 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-01-20 14:44:39,079 DEBUG - HostKey agreed: ssh-ed25519
2021-01-20 14:44:39,079 DEBUG - Cipher agreed: aes128-ctr
2021-01-20 14:44:39,079 DEBUG - MAC agreed: hmac-sha2-256
2021-01-20 14:44:39,079 DEBUG - Compression agreed: none
2021-01-20 14:44:40,050 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-01-20 14:44:40,050 DEBUG - Switch to new keys ...
2021-01-20 14:44:40,051 DEBUG - Adding ssh-ed25519 host key for [106.13.216.53]:28032: a809e22e61ee19c3cded3d4b450df142
2021-01-20 14:44:40,052 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-01-20 14:44:40,128 DEBUG - userauth is OK
2021-01-20 14:44:45,252 INFO - Authentication (publickey) successful!
2021-01-20 14:44:45,256 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-01-20 14:44:45,277 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-01-20 14:44:45,277 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-01-20 14:44:45,277 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-01-20 14:44:45,502 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-01-20 14:44:45,502 DEBUG - Secsh channel 0 opened.
2021-01-20 14:44:45,778 DEBUG - [chan 0] Sesch channel 0 request ok
2021-01-20 14:44:45,802 DEBUG - [chan 0] Sesch channel 0 request ok
2021-01-20 14:44:45,802 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-01-20 14:44:45,822 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-01-20 14:44:45,823 DEBUG - Secsh channel 1 opened.
2021-01-20 14:44:45,860 DEBUG - [chan 1] Sesch channel 1 request ok
2021-01-20 14:44:45,908 DEBUG - [chan 1] EOF received (1)
2021-01-20 14:44:45,909 DEBUG - [chan 1] EOF sent (1)
2021-01-20 14:44:45,910 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-01-20 14:44:46,659 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-01-20 14:44:46,659 DEBUG - Secsh channel 2 opened.
2021-01-20 14:44:46,705 DEBUG - [chan 2] Sesch channel 2 request ok
2021-01-20 14:44:46,717 DEBUG - [chan 2] EOF received (2)
2021-01-20 14:44:46,717 DEBUG - [chan 2] EOF sent (2)
2021-01-20 14:44:46,719 DEBUG - [chan 3] Max packet in: 32768 bytes
2021-01-20 14:44:46,798 DEBUG - [chan 3] Max packet out: 32768 bytes
2021-01-20 14:44:46,798 DEBUG - Secsh channel 3 opened.
2021-01-20 14:44:46,844 DEBUG - [chan 3] Sesch channel 3 request ok
2021-01-20 14:44:46,856 DEBUG - [chan 3] EOF received (3)
2021-01-20 14:44:46,856 DEBUG - [chan 3] EOF sent (3)
2021-01-20 14:44:46,857 DEBUG - EOF in transport thread
2021-01-20 14:44:46,894 ERROR - Internal Server Error: /vpn-manager/initialization/SSRinitlogs/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/app/argus/SSRCHECKER/views.py", line 229, in SSRinitlogs
    SSRsave().ssrlogs(str(request.user.username))
  File "/app/argus_final/app/argus/SSRCHECKER/process.py", line 2086, in ssrlogs
    PORT=ssrinfo['ssr_port'],
TypeError: string indices must be integers, not str
2021-01-20 14:49:08,452 DEBUG - starting thread (client mode): 0xb305bd10L
2021-01-20 14:49:08,452 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-01-20 14:49:08,477 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-01-20 14:49:08,478 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-01-20 14:49:08,497 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-01-20 14:49:08,498 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-01-20 14:49:08,498 DEBUG - HostKey agreed: ssh-ed25519
2021-01-20 14:49:08,498 DEBUG - Cipher agreed: aes128-ctr
2021-01-20 14:49:08,498 DEBUG - MAC agreed: hmac-sha2-256
2021-01-20 14:49:08,498 DEBUG - Compression agreed: none
2021-01-20 14:49:08,565 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-01-20 14:49:08,566 DEBUG - Switch to new keys ...
2021-01-20 14:49:08,570 DEBUG - Adding ssh-ed25519 host key for [106.13.216.53]:28032: a809e22e61ee19c3cded3d4b450df142
2021-01-20 14:49:08,571 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-01-20 14:49:08,872 DEBUG - userauth is OK
2021-01-20 14:49:13,982 INFO - Authentication (publickey) successful!
2021-01-20 14:49:13,989 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-01-20 14:49:14,009 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-01-20 14:49:14,009 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-01-20 14:49:14,010 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-01-20 14:49:14,068 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-01-20 14:49:14,068 DEBUG - Secsh channel 0 opened.
2021-01-20 14:49:14,112 DEBUG - [chan 0] Sesch channel 0 request ok
2021-01-20 14:49:14,136 DEBUG - [chan 0] Sesch channel 0 request ok
2021-01-20 14:49:14,137 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-01-20 14:49:14,158 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-01-20 14:49:14,158 DEBUG - Secsh channel 1 opened.
2021-01-20 14:49:14,195 DEBUG - [chan 1] Sesch channel 1 request ok
