2021-03-24 09:08:06,364 DEBUG - (rock.lim) - Successfully loaded and updated table
2021-03-24 11:12:34,070 ERROR - Internal Server Error: /esync/callmeboss-nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-24 11:12:35,466 ERROR - Internal Server Error: /esync/callmeboss-nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-24 15:04:44,617 ERROR - Internal Server Error: /esync/om-cdn_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-24 15:06:33,945 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-24 16:08:27,525 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-25 09:05:06,446 DEBUG - starting thread (client mode): 0xc2358690L
2021-03-25 09:05:06,446 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-25 09:05:06,469 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-25 09:05:06,469 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-25 09:05:06,474 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-25 09:05:06,474 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-25 09:05:06,474 DEBUG - HostKey agreed: ssh-ed25519
2021-03-25 09:05:06,474 DEBUG - Cipher agreed: aes128-ctr
2021-03-25 09:05:06,474 DEBUG - MAC agreed: hmac-sha2-256
2021-03-25 09:05:06,474 DEBUG - Compression agreed: none
2021-03-25 09:05:06,529 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-25 09:05:06,530 DEBUG - Switch to new keys ...
2021-03-25 09:05:06,548 DEBUG - Adding ssh-ed25519 host key for [103.40.8.233]:28032: ea76ce94b93e3e0b925af7530a54fa6f
2021-03-25 09:05:06,549 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-25 09:05:06,578 DEBUG - userauth is OK
2021-03-25 09:05:06,611 INFO - Authentication (publickey) successful!
2021-03-25 09:05:06,622 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-25 09:05:06,628 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-25 09:05:06,628 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-25 09:05:06,628 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-25 09:05:06,672 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-25 09:05:06,673 DEBUG - Secsh channel 0 opened.
2021-03-25 09:05:06,694 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-25 09:05:06,703 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-25 09:05:06,704 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-25 09:05:06,709 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-25 09:05:06,709 DEBUG - Secsh channel 1 opened.
2021-03-25 09:05:06,720 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-25 09:05:13,286 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-25 09:05:13,288 DEBUG - [chan 1] EOF received (1)
2021-03-25 09:05:13,289 DEBUG - [chan 1] EOF sent (1)
2021-03-25 09:05:13,293 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-25 09:05:13,293 DEBUG - Secsh channel 2 opened.
2021-03-25 09:05:13,344 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-25 09:05:13,363 DEBUG - [chan 2] EOF received (2)
2021-03-25 09:05:13,363 DEBUG - [chan 2] EOF sent (2)
2021-03-25 09:05:13,365 DEBUG - EOF in transport thread
2021-03-25 15:47:42,261 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 246-248: ordinal not in range(128)
2021-03-25 15:52:33,909 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 246-248: ordinal not in range(128)
2021-03-25 15:58:29,373 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 250-252: ordinal not in range(128)
2021-03-25 16:20:31,027 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-25 16:20:58,764 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-25 17:26:11,323 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 247-249: ordinal not in range(128)
2021-03-25 21:59:48,461 DEBUG - starting thread (client mode): 0xc09002d0L
2021-03-25 21:59:48,461 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-25 21:59:48,753 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-25 21:59:48,754 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-25 21:59:49,001 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-25 21:59:49,001 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-25 21:59:49,002 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-25 21:59:49,002 DEBUG - Cipher agreed: aes128-ctr
2021-03-25 21:59:49,002 DEBUG - MAC agreed: hmac-sha2-256
2021-03-25 21:59:49,002 DEBUG - Compression agreed: none
2021-03-25 21:59:49,256 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-25 21:59:49,257 DEBUG - Switch to new keys ...
2021-03-25 21:59:49,267 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.19.184]:28032: eebe5f304e31a324d4aac75716449e42
2021-03-25 21:59:49,268 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-25 21:59:49,793 DEBUG - userauth is OK
2021-03-25 21:59:55,261 INFO - Authentication (publickey) successful!
2021-03-25 21:59:55,276 DEBUG - EOF in transport thread
2021-03-25 21:59:58,531 DEBUG - starting thread (client mode): 0xc1445050L
2021-03-25 21:59:58,531 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-25 21:59:58,816 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-25 21:59:58,816 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-25 21:59:59,063 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-25 21:59:59,063 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-25 21:59:59,063 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-25 21:59:59,063 DEBUG - Cipher agreed: aes128-ctr
2021-03-25 21:59:59,063 DEBUG - MAC agreed: hmac-sha2-256
2021-03-25 21:59:59,063 DEBUG - Compression agreed: none
2021-03-25 21:59:59,353 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-25 21:59:59,353 DEBUG - Switch to new keys ...
2021-03-25 21:59:59,355 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.19.184]:28032: eebe5f304e31a324d4aac75716449e42
2021-03-25 21:59:59,356 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-25 21:59:59,884 DEBUG - userauth is OK
2021-03-25 22:00:05,362 INFO - Authentication (publickey) successful!
2021-03-25 22:00:05,365 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-25 22:00:06,150 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-25 22:00:06,436 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-25 22:00:06,436 DEBUG - Secsh channel 0 opened.
2021-03-25 22:00:06,692 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-25 22:00:06,942 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-25 22:00:06,943 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-25 22:00:07,192 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-25 22:00:07,192 DEBUG - Secsh channel 1 opened.
2021-03-25 22:00:07,461 DEBUG - [chan 1] Sesch channel 1 request ok
