2021-03-14 16:28:05,022 DEBUG - (james.cadelina) - Successfully loaded and updated table
2021-03-14 16:36:24,160 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-15 08:13:13,430 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-15 08:53:09,120 DEBUG - (james.cadelina) - Successfully loaded and updated table
2021-03-15 08:59:42,536 DEBUG - (teckxiu) - Successfully loaded and updated table
2021-03-15 09:00:14,401 DEBUG - (teckxiu) - Successfully loaded and updated table
2021-03-15 09:00:35,406 DEBUG - (teckxiu) - Successfully loaded and updated table
2021-03-15 09:01:44,475 DEBUG - (teckxiu) - Successfully loaded and updated table
2021-03-15 09:03:21,468 DEBUG - (teckxiu) - Successfully loaded and updated table
2021-03-15 09:03:28,553 DEBUG - (teckxiu) - Successfully loaded and updated table
2021-03-15 15:15:20,009 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-15 15:27:24,169 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-15 19:37:41,742 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-15 22:04:54,212 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-15 22:04:57,292 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-15 22:05:02,411 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-15 22:05:22,896 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:07:04,278 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-16 08:18:19,242 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:22,441 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:33,581 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:39,422 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:21:20,435 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:21:23,096 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:46:41,899 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 08:47:57,491 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 08:48:32,366 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 08:49:05,254 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 08:58:05,728 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 11:47:41,267 DEBUG - (james.cadelina) - Successfully loaded and updated table
2021-03-16 12:55:37,384 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 335-336: ordinal not in range(128)
2021-03-16 13:06:11,119 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 332-333: ordinal not in range(128)
2021-03-16 13:13:38,009 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 332-333: ordinal not in range(128)
2021-03-16 13:21:42,754 ERROR - Internal Server Error: /domains/ssladded
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view domains.views.add_sslchecker didn't return an HttpResponse object. It returned None instead.
2021-03-16 13:22:10,786 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-16 13:25:57,673 DEBUG - (james.cadelina) - Successfully loaded and updated table
2021-03-16 14:04:35,265 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-16 14:12:08,843 DEBUG - (james.cadelina) - Successfully loaded and updated table
2021-03-16 14:14:46,921 DEBUG - (emilyn.delacruz) - Successfully loaded and updated table
2021-03-16 16:45:00,199 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 393-395: ordinal not in range(128)
2021-03-16 19:10:53,135 DEBUG - starting thread (client mode): 0xc6b04350L
2021-03-16 19:10:53,136 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-16 19:11:08,150 ERROR - Exception: Error reading SSH protocol banner
2021-03-16 19:11:08,152 ERROR - Traceback (most recent call last):
2021-03-16 19:11:08,152 ERROR -   File "/app/argus_final/venv/lib/python2.7/site-packages/paramiko/transport.py", line 2039, in run
2021-03-16 19:11:08,152 ERROR -     self._check_banner()
2021-03-16 19:11:08,152 ERROR -   File "/app/argus_final/venv/lib/python2.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
2021-03-16 19:11:08,152 ERROR -     "Error reading SSH protocol banner" + str(e)
2021-03-16 19:11:08,152 ERROR - SSHException: Error reading SSH protocol banner
2021-03-16 19:11:08,152 ERROR - 
2021-03-16 20:45:07,249 ERROR - Internal Server Error: /vpn-manager/initialization/SSRinitlogs/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/app/argus/SSRCHECKER/views.py", line 229, in SSRinitlogs
    SSRsave().ssrlogs(str(request.user.username))
  File "/app/argus_final/app/argus/SSRCHECKER/process.py", line 2086, in ssrlogs
    PORT=ssrinfo['ssr_port'],
TypeError: string indices must be integers, not str
2021-03-16 23:46:10,410 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:46:17,633 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:46:32,442 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:46:38,485 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:46:52,836 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:47:30,812 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:47:37,888 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:47:58,307 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:48:04,061 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:48:26,603 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:48:32,878 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:48:39,570 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:48:46,702 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:48:52,883 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:49:04,585 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-17 01:15:11,872 DEBUG - starting thread (client mode): 0xc43c63d0L
2021-03-17 01:15:11,872 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 01:15:11,920 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-17 01:15:11,920 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-17 01:15:11,937 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 01:15:11,937 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-17 01:15:11,937 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-17 01:15:11,937 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 01:15:11,938 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 01:15:11,938 DEBUG - Compression agreed: none
2021-03-17 01:15:11,957 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-17 01:15:11,958 DEBUG - Switch to new keys ...
2021-03-17 01:15:11,974 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.16.94]:28032: 75d1c31170d6257e2001c1129928c81c
2021-03-17 01:15:11,975 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 01:15:12,001 DEBUG - userauth is OK
2021-03-17 01:15:12,059 INFO - Authentication (publickey) successful!
2021-03-17 01:15:12,078 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 01:15:12,464 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 01:15:12,506 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 01:15:12,506 DEBUG - Secsh channel 0 opened.
2021-03-17 01:15:12,523 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:12,531 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:12,531 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 01:15:12,537 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 01:15:12,538 DEBUG - Secsh channel 1 opened.
2021-03-17 01:15:12,548 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 01:15:24,165 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 01:15:24,170 DEBUG - [chan 1] EOF received (1)
2021-03-17 01:15:24,171 DEBUG - [chan 1] EOF sent (1)
2021-03-17 01:15:24,171 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 01:15:24,171 DEBUG - Secsh channel 2 opened.
2021-03-17 01:15:24,178 DEBUG - starting thread (client mode): 0xc51a4f50L
2021-03-17 01:15:24,178 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 01:15:24,206 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.6.1
2021-03-17 01:15:24,206 INFO - Connected (version 2.0, client OpenSSH_6.6.1)
2021-03-17 01:15:24,211 DEBUG - kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 01:15:24,211 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 01:15:24,211 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 01:15:24,211 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 01:15:24,211 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 01:15:24,212 DEBUG - Compression agreed: none
2021-03-17 01:15:24,219 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 01:15:24,233 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 01:15:24,233 DEBUG - Switch to new keys ...
2021-03-17 01:15:24,243 DEBUG - Adding ssh-ed25519 host key for [46.8.198.13]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 01:15:24,244 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 01:15:24,280 DEBUG - userauth is OK
2021-03-17 01:15:24,487 DEBUG - [chan 2] EOF received (2)
2021-03-17 01:15:24,488 DEBUG - [chan 2] EOF sent (2)
2021-03-17 01:15:24,489 DEBUG - EOF in transport thread
2021-03-17 01:15:29,319 INFO - Authentication (publickey) successful!
2021-03-17 01:15:29,341 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 01:15:29,345 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 01:15:29,388 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 01:15:29,388 DEBUG - Secsh channel 0 opened.
2021-03-17 01:15:29,413 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:29,421 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:29,421 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 01:15:29,426 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 01:15:29,426 DEBUG - Secsh channel 1 opened.
2021-03-17 01:15:29,437 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 01:15:41,872 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 01:15:41,874 DEBUG - [chan 1] EOF received (1)
2021-03-17 01:15:41,874 DEBUG - [chan 1] EOF sent (1)
2021-03-17 01:15:41,877 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 01:15:41,877 DEBUG - Secsh channel 2 opened.
2021-03-17 01:15:41,926 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 01:15:41,981 DEBUG - [chan 2] EOF received (2)
2021-03-17 01:15:41,982 DEBUG - [chan 2] EOF sent (2)
2021-03-17 01:15:41,983 DEBUG - EOF in transport thread
2021-03-17 02:10:25,420 DEBUG - starting thread (client mode): 0xc487c510L
2021-03-17 02:10:25,421 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 02:10:25,437 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 02:10:25,438 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 02:10:25,440 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 02:10:25,440 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 02:10:25,440 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 02:10:25,441 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 02:10:25,441 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 02:10:25,441 DEBUG - Compression agreed: none
2021-03-17 02:10:25,494 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 02:10:25,495 DEBUG - Switch to new keys ...
2021-03-17 02:10:25,522 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 02:10:25,524 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 02:10:25,538 DEBUG - userauth is OK
2021-03-17 02:10:25,604 INFO - Authentication (publickey) failed.
2021-03-17 02:10:26,333 DEBUG - starting thread (client mode): 0xc4840810L
2021-03-17 02:10:26,333 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 02:10:26,350 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 02:10:26,351 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 02:10:26,353 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 02:10:26,354 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 02:10:26,354 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 02:10:26,354 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 02:10:26,354 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 02:10:26,354 DEBUG - Compression agreed: none
2021-03-17 02:10:26,405 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 02:10:26,405 DEBUG - Switch to new keys ...
2021-03-17 02:10:26,434 DEBUG - Adding ssh-ed25519 host key for [58.64.177.241]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 02:10:26,435 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 02:10:26,449 DEBUG - userauth is OK
2021-03-17 02:10:26,508 INFO - Authentication (publickey) successful!
2021-03-17 02:10:26,510 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 02:10:26,526 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 02:10:26,526 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 02:10:26,526 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 02:10:26,568 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 02:10:26,568 DEBUG - Secsh channel 0 opened.
2021-03-17 02:10:26,581 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 02:10:26,587 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 02:10:26,588 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 02:10:26,591 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 02:10:26,591 DEBUG - Secsh channel 1 opened.
2021-03-17 02:10:26,599 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 02:10:32,920 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 02:10:32,942 DEBUG - [chan 1] EOF received (1)
2021-03-17 02:10:32,943 DEBUG - [chan 1] EOF sent (1)
2021-03-17 02:10:32,944 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 02:10:32,944 DEBUG - Secsh channel 2 opened.
2021-03-17 02:10:32,949 DEBUG - starting thread (client mode): 0xc487c990L
2021-03-17 02:10:32,949 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 02:10:32,969 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 02:10:32,969 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 02:10:32,972 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 02:10:32,972 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 02:10:32,972 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 02:10:32,972 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 02:10:32,972 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 02:10:32,973 DEBUG - Compression agreed: none
2021-03-17 02:10:32,991 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 02:10:33,021 DEBUG - [chan 2] EOF received (2)
2021-03-17 02:10:33,022 DEBUG - [chan 2] EOF sent (2)
2021-03-17 02:10:33,022 DEBUG - EOF in transport thread
2021-03-17 02:10:33,029 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 02:10:33,030 DEBUG - Switch to new keys ...
2021-03-17 02:10:33,050 DEBUG - Adding ssh-ed25519 host key for [154.209.4.56]:28032: fb679dcdfda01a6424c0563de3f822e1
2021-03-17 02:10:33,051 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 02:10:33,075 DEBUG - userauth is OK
2021-03-17 02:10:33,107 INFO - Authentication (publickey) successful!
2021-03-17 02:10:33,119 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 02:10:33,126 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 02:10:33,126 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 02:10:33,127 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 02:10:33,169 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 02:10:33,169 DEBUG - Secsh channel 0 opened.
2021-03-17 02:10:33,192 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 02:10:33,200 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 02:10:33,200 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 02:10:33,207 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 02:10:33,207 DEBUG - Secsh channel 1 opened.
2021-03-17 02:10:33,220 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 02:10:39,720 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 02:10:39,722 DEBUG - [chan 1] EOF received (1)
2021-03-17 02:10:39,723 DEBUG - [chan 1] EOF sent (1)
2021-03-17 02:10:39,724 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 02:10:39,724 DEBUG - Secsh channel 2 opened.
2021-03-17 02:10:39,773 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 02:10:39,796 DEBUG - [chan 2] EOF received (2)
2021-03-17 02:10:39,796 DEBUG - [chan 2] EOF sent (2)
2021-03-17 02:10:39,797 DEBUG - EOF in transport thread
2021-03-17 02:11:25,440 DEBUG - EOF in transport thread
2021-03-17 03:52:13,787 DEBUG - starting thread (client mode): 0xc4729c10L
2021-03-17 03:52:13,788 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 03:52:13,844 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-17 03:52:13,844 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-17 03:52:13,854 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 03:52:13,854 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-17 03:52:13,855 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-17 03:52:13,855 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 03:52:13,855 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 03:52:13,855 DEBUG - Compression agreed: none
2021-03-17 03:52:13,862 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-17 03:52:13,862 DEBUG - Switch to new keys ...
2021-03-17 03:52:13,889 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.16.109]:28032: 75d1c31170d6257e2001c1129928c81c
2021-03-17 03:52:13,890 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 03:52:13,906 DEBUG - userauth is OK
2021-03-17 03:52:14,008 INFO - Authentication (publickey) successful!
2021-03-17 03:52:14,024 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 03:52:14,210 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 03:52:14,252 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 03:52:14,252 DEBUG - Secsh channel 0 opened.
2021-03-17 03:52:14,285 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:52:14,294 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:52:14,294 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 03:52:14,298 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 03:52:14,298 DEBUG - Secsh channel 1 opened.
2021-03-17 03:52:14,316 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 03:52:15,027 DEBUG - [chan 1] EOF received (1)
2021-03-17 03:52:15,028 DEBUG - [chan 1] EOF sent (1)
2021-03-17 03:52:15,029 DEBUG - EOF in transport thread
2021-03-17 03:52:15,043 DEBUG - starting thread (client mode): 0xc43bcc10L
2021-03-17 03:52:15,043 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 03:52:15,148 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-17 03:52:15,148 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-17 03:52:15,179 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 03:52:15,180 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-17 03:52:15,180 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-17 03:52:15,180 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 03:52:15,180 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 03:52:15,180 DEBUG - Compression agreed: none
2021-03-17 03:52:15,223 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-17 03:52:15,224 DEBUG - Switch to new keys ...
2021-03-17 03:52:15,245 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.16.109]:28032: 75d1c31170d6257e2001c1129928c81c
2021-03-17 03:52:15,245 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 03:52:15,285 DEBUG - userauth is OK
2021-03-17 03:52:15,439 INFO - Authentication (publickey) successful!
2021-03-17 03:52:15,447 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 03:52:15,547 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 03:52:15,589 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 03:52:15,589 DEBUG - Secsh channel 0 opened.
2021-03-17 03:52:15,627 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:52:15,635 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:52:15,635 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 03:52:15,653 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 03:52:15,653 DEBUG - Secsh channel 1 opened.
2021-03-17 03:52:15,676 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 03:52:16,409 DEBUG - [chan 1] EOF received (1)
2021-03-17 03:52:16,409 DEBUG - [chan 1] EOF sent (1)
2021-03-17 03:52:16,410 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 03:52:16,473 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 03:52:16,473 DEBUG - Secsh channel 2 opened.
2021-03-17 03:52:16,501 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 03:52:17,201 DEBUG - [chan 2] EOF received (2)
2021-03-17 03:52:17,201 DEBUG - [chan 2] EOF sent (2)
2021-03-17 03:52:17,203 DEBUG - [chan 3] Max packet in: 32768 bytes
2021-03-17 03:52:17,273 DEBUG - [chan 3] Max packet out: 32768 bytes
2021-03-17 03:52:17,273 DEBUG - Secsh channel 3 opened.
2021-03-17 03:52:17,315 DEBUG - [chan 3] Sesch channel 3 request ok
2021-03-17 03:52:17,654 DEBUG - [chan 3] EOF received (3)
2021-03-17 03:52:17,655 DEBUG - [chan 3] EOF sent (3)
2021-03-17 03:52:17,656 DEBUG - EOF in transport thread
2021-03-17 03:52:17,693 DEBUG - starting thread (client mode): 0xc39a2d50L
2021-03-17 03:52:17,693 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 03:52:17,723 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-17 03:52:17,724 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-17 03:52:17,734 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 03:52:17,734 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-17 03:52:17,734 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-17 03:52:17,735 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 03:52:17,735 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 03:52:17,735 DEBUG - Compression agreed: none
2021-03-17 03:52:17,750 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-17 03:52:17,750 DEBUG - Switch to new keys ...
2021-03-17 03:52:17,759 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.27.109.180]:28032: 75d1c31170d6257e2001c1129928c81c
2021-03-17 03:52:17,760 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 03:52:17,798 DEBUG - userauth is OK
2021-03-17 03:52:17,896 INFO - Authentication (publickey) successful!
2021-03-17 03:52:17,927 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 03:52:18,212 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 03:52:18,254 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 03:52:18,254 DEBUG - Secsh channel 0 opened.
2021-03-17 03:52:18,300 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:52:18,310 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:52:18,311 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 03:52:18,320 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 03:52:18,320 DEBUG - Secsh channel 1 opened.
2021-03-17 03:52:18,355 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 03:52:19,133 DEBUG - [chan 1] EOF received (1)
2021-03-17 03:52:19,134 DEBUG - [chan 1] EOF sent (1)
2021-03-17 03:52:19,135 DEBUG - EOF in transport thread
2021-03-17 03:52:19,149 DEBUG - starting thread (client mode): 0xc39a2e10L
2021-03-17 03:52:19,149 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 03:52:19,288 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-17 03:52:19,288 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-17 03:52:19,305 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 03:52:19,305 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-17 03:52:19,306 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-17 03:52:19,306 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 03:52:19,306 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 03:52:19,306 DEBUG - Compression agreed: none
2021-03-17 03:52:19,322 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-17 03:52:19,323 DEBUG - Switch to new keys ...
2021-03-17 03:52:19,352 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.27.109.180]:28032: 75d1c31170d6257e2001c1129928c81c
2021-03-17 03:52:19,353 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 03:52:19,389 DEBUG - userauth is OK
2021-03-17 03:52:19,526 INFO - Authentication (publickey) successful!
2021-03-17 03:52:19,555 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 03:52:19,667 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 03:52:19,708 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 03:52:19,708 DEBUG - Secsh channel 0 opened.
2021-03-17 03:52:19,742 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:52:19,759 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:52:19,760 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 03:52:19,780 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 03:52:19,781 DEBUG - Secsh channel 1 opened.
2021-03-17 03:52:19,815 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 03:52:20,538 DEBUG - [chan 1] EOF received (1)
2021-03-17 03:52:20,539 DEBUG - [chan 1] EOF sent (1)
2021-03-17 03:52:20,540 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 03:52:20,605 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 03:52:20,605 DEBUG - Secsh channel 2 opened.
2021-03-17 03:52:20,616 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 03:52:21,427 DEBUG - [chan 2] EOF received (2)
2021-03-17 03:52:21,427 DEBUG - [chan 2] EOF sent (2)
2021-03-17 03:52:21,428 DEBUG - [chan 3] Max packet in: 32768 bytes
2021-03-17 03:52:21,483 DEBUG - [chan 3] Max packet out: 32768 bytes
2021-03-17 03:52:21,483 DEBUG - Secsh channel 3 opened.
2021-03-17 03:52:21,503 DEBUG - [chan 3] Sesch channel 3 request ok
2021-03-17 03:52:21,842 DEBUG - [chan 3] EOF received (3)
2021-03-17 03:52:21,843 DEBUG - [chan 3] EOF sent (3)
2021-03-17 03:52:21,844 DEBUG - EOF in transport thread
2021-03-17 03:59:04,883 DEBUG - starting thread (client mode): 0xc4514510L
2021-03-17 03:59:04,884 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 03:59:04,939 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 03:59:04,939 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 03:59:04,945 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 03:59:04,945 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 03:59:04,945 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 03:59:04,945 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 03:59:04,946 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 03:59:04,946 DEBUG - Compression agreed: none
2021-03-17 03:59:04,969 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 03:59:04,969 DEBUG - Switch to new keys ...
2021-03-17 03:59:04,985 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 03:59:04,986 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 03:59:05,013 DEBUG - userauth is OK
2021-03-17 03:59:05,254 INFO - Authentication (publickey) successful!
2021-03-17 03:59:05,256 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 03:59:05,334 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 03:59:05,334 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 03:59:05,334 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 03:59:05,375 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 03:59:05,375 DEBUG - Secsh channel 0 opened.
2021-03-17 03:59:05,396 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:59:05,406 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:59:05,407 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 03:59:05,410 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 03:59:05,410 DEBUG - Secsh channel 1 opened.
2021-03-17 03:59:05,430 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 03:59:05,522 DEBUG - [chan 1] EOF received (1)
2021-03-17 03:59:05,523 DEBUG - [chan 1] EOF sent (1)
2021-03-17 03:59:05,524 DEBUG - EOF in transport thread
2021-03-17 03:59:05,536 DEBUG - starting thread (client mode): 0xc453bf10L
2021-03-17 03:59:05,536 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 03:59:05,586 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 03:59:05,586 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 03:59:05,592 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 03:59:05,592 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 03:59:05,592 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 03:59:05,592 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 03:59:05,592 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 03:59:05,592 DEBUG - Compression agreed: none
2021-03-17 03:59:05,616 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 03:59:05,616 DEBUG - Switch to new keys ...
2021-03-17 03:59:05,637 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 03:59:05,638 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 03:59:05,660 DEBUG - userauth is OK
2021-03-17 03:59:05,730 INFO - Authentication (publickey) successful!
2021-03-17 03:59:05,740 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 03:59:05,768 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 03:59:05,768 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 03:59:05,768 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 03:59:05,810 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 03:59:05,810 DEBUG - Secsh channel 0 opened.
2021-03-17 03:59:05,848 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:59:05,859 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 03:59:05,860 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 03:59:05,863 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 03:59:05,863 DEBUG - Secsh channel 1 opened.
2021-03-17 03:59:05,882 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 03:59:05,950 DEBUG - [chan 1] EOF received (1)
2021-03-17 03:59:05,950 DEBUG - [chan 1] EOF sent (1)
2021-03-17 03:59:05,951 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 03:59:05,989 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 03:59:05,989 DEBUG - Secsh channel 2 opened.
2021-03-17 03:59:06,026 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 03:59:06,093 DEBUG - [chan 2] EOF received (2)
2021-03-17 03:59:06,094 DEBUG - [chan 2] EOF sent (2)
2021-03-17 03:59:06,095 DEBUG - [chan 3] Max packet in: 32768 bytes
2021-03-17 03:59:06,140 DEBUG - [chan 3] Max packet out: 32768 bytes
2021-03-17 03:59:06,140 DEBUG - Secsh channel 3 opened.
2021-03-17 03:59:06,172 DEBUG - [chan 3] Sesch channel 3 request ok
2021-03-17 03:59:06,235 DEBUG - [chan 3] EOF received (3)
2021-03-17 03:59:06,236 DEBUG - [chan 3] EOF sent (3)
2021-03-17 03:59:06,237 DEBUG - EOF in transport thread
2021-03-17 12:25:18,779 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 373-375: ordinal not in range(128)
2021-03-17 17:21:19,185 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 207-208: ordinal not in range(128)
2021-03-18 09:34:35,968 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 233-235: ordinal not in range(128)
2021-03-18 09:37:39,468 ERROR - Internal Server Error: /domains/ssladded
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view domains.views.add_sslchecker didn't return an HttpResponse object. It returned None instead.
2021-03-18 11:37:07,616 ERROR - Internal Server Error: /domains/ssladded
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view domains.views.add_sslchecker didn't return an HttpResponse object. It returned None instead.
2021-03-18 15:53:38,628 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-18 21:12:32,334 DEBUG - starting thread (client mode): 0xc43573d0L
2021-03-18 21:12:32,345 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-18 21:12:32,364 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.6.1
2021-03-18 21:12:32,364 INFO - Connected (version 2.0, client OpenSSH_6.6.1)
2021-03-18 21:12:32,369 DEBUG - kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-18 21:12:32,369 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-18 21:12:32,369 DEBUG - HostKey agreed: ssh-ed25519
2021-03-18 21:12:32,370 DEBUG - Cipher agreed: aes128-ctr
2021-03-18 21:12:32,370 DEBUG - MAC agreed: hmac-sha2-256
2021-03-18 21:12:32,370 DEBUG - Compression agreed: none
2021-03-18 21:12:32,401 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-18 21:12:32,402 DEBUG - Switch to new keys ...
2021-03-18 21:12:32,410 DEBUG - Adding ssh-ed25519 host key for [46.8.198.13]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-18 21:12:32,412 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-18 21:12:32,449 DEBUG - userauth is OK
2021-03-18 21:12:32,901 INFO - Authentication (publickey) successful!
2021-03-18 21:12:32,917 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-18 21:12:32,930 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-18 21:12:32,973 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-18 21:12:32,973 DEBUG - Secsh channel 0 opened.
2021-03-18 21:12:32,989 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-18 21:12:32,997 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-18 21:12:32,997 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-18 21:12:33,001 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-18 21:12:33,002 DEBUG - Secsh channel 1 opened.
2021-03-18 21:12:33,012 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-18 21:12:42,898 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-18 21:12:42,900 DEBUG - [chan 1] EOF received (1)
2021-03-18 21:12:42,901 DEBUG - [chan 1] EOF sent (1)
2021-03-18 21:12:42,904 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-18 21:12:42,904 DEBUG - Secsh channel 2 opened.
2021-03-18 21:12:42,954 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-18 21:12:43,012 DEBUG - [chan 2] EOF received (2)
2021-03-18 21:12:43,012 DEBUG - [chan 2] EOF sent (2)
2021-03-18 21:12:43,014 DEBUG - EOF in transport thread
2021-03-19 02:38:48,606 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2021-03-19 02:38:55,163 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2021-03-19 15:05:55,240 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 270-273: ordinal not in range(128)
2021-03-19 15:08:13,415 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 290-296: ordinal not in range(128)
2021-03-19 15:09:41,685 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 280-286: ordinal not in range(128)
2021-03-20 07:43:25,864 DEBUG - starting thread (client mode): 0xc3429d10L
2021-03-20 07:43:25,865 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-20 07:43:25,882 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-20 07:43:25,882 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-20 07:43:25,886 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-20 07:43:25,887 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-20 07:43:25,887 DEBUG - HostKey agreed: ssh-ed25519
2021-03-20 07:43:25,887 DEBUG - Cipher agreed: aes128-ctr
2021-03-20 07:43:25,887 DEBUG - MAC agreed: hmac-sha2-256
2021-03-20 07:43:25,887 DEBUG - Compression agreed: none
2021-03-20 07:43:25,940 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-20 07:43:25,941 DEBUG - Switch to new keys ...
2021-03-20 07:43:25,966 DEBUG - Adding ssh-ed25519 host key for [103.40.8.233]:28032: ea76ce94b93e3e0b925af7530a54fa6f
2021-03-20 07:43:25,967 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-20 07:43:25,987 DEBUG - userauth is OK
2021-03-20 07:43:31,020 INFO - Authentication (publickey) successful!
2021-03-20 07:43:31,036 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-20 07:43:31,040 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-20 07:43:31,040 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-20 07:43:31,041 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-20 07:43:31,084 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-20 07:43:31,084 DEBUG - Secsh channel 0 opened.
2021-03-20 07:43:31,107 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 07:43:31,113 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 07:43:31,114 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-20 07:43:31,119 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-20 07:43:31,119 DEBUG - Secsh channel 1 opened.
2021-03-20 07:43:31,130 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-20 07:43:41,825 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-20 07:43:41,826 DEBUG - [chan 1] EOF received (1)
2021-03-20 07:43:41,827 DEBUG - [chan 1] EOF sent (1)
2021-03-20 07:43:41,830 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-20 07:43:41,830 DEBUG - Secsh channel 2 opened.
2021-03-20 07:43:41,880 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-20 07:43:41,898 DEBUG - [chan 2] EOF received (2)
2021-03-20 07:43:41,899 DEBUG - [chan 2] EOF sent (2)
2021-03-20 07:43:41,900 DEBUG - EOF in transport thread
2021-03-22 05:54:10,133 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-22 05:55:32,425 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-22 05:55:44,291 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-22 05:56:56,122 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-22 08:34:04,607 ERROR - Internal Server Error: /esync/om-clientgamecalled_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-22 08:37:46,279 ERROR - Internal Server Error: /esync/om-clientgamecalled_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-22 08:40:20,486 ERROR - Internal Server Error: /esync/om-clientgamecalled_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-22 08:44:15,167 ERROR - Internal Server Error: /esync/om-clientgamecalled_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
