2020-02-04 23:13:35,289 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:13:44,870 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:18:05,289 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:18:11,157 ERROR - Internal Server Error: /ssl-checker/bulkAdded
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/app/argus/SSLDOMAINS/views.py", line 192, in bulkAdd
    "object_list"   : query_set,
UnboundLocalError: local variable 'query_set' referenced before assignment
2020-02-04 23:18:59,710 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:20:02,201 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:25:05,132 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:30:20,667 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:30:27,578 ERROR - Internal Server Error: /ssl-checker/bulkAdded
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/app/argus/SSLDOMAINS/views.py", line 196, in bulkAdd
    return render(request, 'SSLDOMAINS/home.html', args)
UnboundLocalError: local variable 'args' referenced before assignment
2020-02-04 23:35:38,723 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:36:04,417 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:36:11,137 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:39:47,673 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-02-04 23:41:39,515 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
