2021-02-21 08:02:42,589 DEBUG - (james.cadelina) - Successfully loaded and updated table
2021-02-21 15:07:32,835 DEBUG - starting thread (client mode): 0xb9885190L
2021-02-21 15:07:32,835 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-21 15:07:32,884 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-02-21 15:07:32,884 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-02-21 15:07:32,900 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-21 15:07:32,901 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-02-21 15:07:32,901 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-02-21 15:07:32,901 DEBUG - Cipher agreed: aes128-ctr
2021-02-21 15:07:32,901 DEBUG - MAC agreed: hmac-sha2-256
2021-02-21 15:07:32,901 DEBUG - Compression agreed: none
2021-02-21 15:07:32,928 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-02-21 15:07:32,928 DEBUG - Switch to new keys ...
2021-02-21 15:07:32,937 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.16.6]:28032: 75d1c31170d6257e2001c1129928c81c
2021-02-21 15:07:32,938 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-21 15:07:32,998 DEBUG - userauth is OK
2021-02-21 15:07:33,934 INFO - Authentication (publickey) successful!
2021-02-21 15:07:33,945 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-21 15:07:34,360 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-21 15:07:34,412 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-21 15:07:34,412 DEBUG - Secsh channel 0 opened.
2021-02-21 15:07:34,432 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-21 15:07:34,447 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-21 15:07:34,448 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-21 15:07:34,460 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-21 15:07:34,460 DEBUG - Secsh channel 1 opened.
2021-02-21 15:07:34,481 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-21 15:07:45,903 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-21 15:07:45,905 DEBUG - [chan 1] EOF received (1)
2021-02-21 15:07:45,905 DEBUG - [chan 1] EOF sent (1)
2021-02-21 15:07:45,911 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-21 15:07:45,911 DEBUG - Secsh channel 2 opened.
2021-02-21 15:07:45,958 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-21 15:07:46,214 DEBUG - [chan 2] EOF received (2)
2021-02-21 15:07:46,215 DEBUG - [chan 2] EOF sent (2)
2021-02-21 15:07:46,216 DEBUG - EOF in transport thread
2021-02-21 20:51:43,490 DEBUG - starting thread (client mode): 0xb98c1990L
2021-02-21 20:51:43,490 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-21 20:51:43,509 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-21 20:51:43,509 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-21 20:51:43,515 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-21 20:51:43,515 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-21 20:51:43,515 DEBUG - HostKey agreed: ssh-ed25519
2021-02-21 20:51:43,515 DEBUG - Cipher agreed: aes128-ctr
2021-02-21 20:51:43,515 DEBUG - MAC agreed: hmac-sha2-256
2021-02-21 20:51:43,516 DEBUG - Compression agreed: none
2021-02-21 20:51:43,533 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-21 20:51:43,533 DEBUG - Switch to new keys ...
2021-02-21 20:51:43,555 DEBUG - Adding ssh-ed25519 host key for [123.1.189.31]:28032: f0e839335cba3de5a05d8dd23be98e47
2021-02-21 20:51:43,556 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-21 20:51:43,574 DEBUG - userauth is OK
2021-02-21 20:51:48,631 INFO - Authentication (publickey) successful!
2021-02-21 20:51:48,662 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-21 20:51:48,664 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-21 20:51:48,664 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-21 20:51:48,664 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-21 20:51:48,705 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-21 20:51:48,705 DEBUG - Secsh channel 0 opened.
2021-02-21 20:51:48,734 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-21 20:51:48,744 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-21 20:51:48,745 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-21 20:51:48,748 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-21 20:51:48,748 DEBUG - Secsh channel 1 opened.
2021-02-21 20:51:48,762 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-21 20:51:48,801 DEBUG - [chan 1] EOF received (1)
2021-02-21 20:51:48,802 DEBUG - [chan 1] EOF sent (1)
2021-02-21 20:51:48,803 DEBUG - EOF in transport thread
2021-02-21 20:51:48,812 DEBUG - starting thread (client mode): 0xb8c38910L
2021-02-21 20:51:48,812 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-21 20:51:48,860 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-21 20:51:48,860 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-21 20:51:48,865 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-21 20:51:48,866 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-21 20:51:48,866 DEBUG - HostKey agreed: ssh-ed25519
2021-02-21 20:51:48,866 DEBUG - Cipher agreed: aes128-ctr
2021-02-21 20:51:48,866 DEBUG - MAC agreed: hmac-sha2-256
2021-02-21 20:51:48,866 DEBUG - Compression agreed: none
2021-02-21 20:51:48,884 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-21 20:51:48,884 DEBUG - Switch to new keys ...
2021-02-21 20:51:48,913 DEBUG - Adding ssh-ed25519 host key for [123.1.189.31]:28032: f0e839335cba3de5a05d8dd23be98e47
2021-02-21 20:51:48,914 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-21 20:51:48,927 DEBUG - userauth is OK
2021-02-21 20:51:53,988 INFO - Authentication (publickey) successful!
2021-02-21 20:51:54,016 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-21 20:51:54,019 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-21 20:51:54,019 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-21 20:51:54,020 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-21 20:51:54,060 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-21 20:51:54,060 DEBUG - Secsh channel 0 opened.
2021-02-21 20:51:54,090 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-21 20:51:54,101 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-21 20:51:54,101 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-21 20:51:54,103 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-21 20:51:54,104 DEBUG - Secsh channel 1 opened.
2021-02-21 20:51:54,112 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-21 20:51:54,143 DEBUG - [chan 1] EOF received (1)
2021-02-21 20:51:54,144 DEBUG - [chan 1] EOF sent (1)
2021-02-21 20:51:54,144 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-21 20:51:54,160 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-21 20:51:54,161 DEBUG - Secsh channel 2 opened.
2021-02-21 20:51:54,173 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-21 20:51:54,190 DEBUG - [chan 2] EOF received (2)
2021-02-21 20:51:54,191 DEBUG - [chan 2] EOF sent (2)
2021-02-21 20:51:54,192 DEBUG - [chan 3] Max packet in: 32768 bytes
2021-02-21 20:51:54,234 DEBUG - [chan 3] Max packet out: 32768 bytes
2021-02-21 20:51:54,234 DEBUG - Secsh channel 3 opened.
2021-02-21 20:51:54,268 DEBUG - [chan 3] Sesch channel 3 request ok
2021-02-21 20:51:54,285 DEBUG - [chan 3] EOF received (3)
2021-02-21 20:51:54,286 DEBUG - [chan 3] EOF sent (3)
2021-02-21 20:51:54,287 DEBUG - EOF in transport thread
2021-02-22 08:03:13,405 DEBUG - starting thread (client mode): 0xb9bd7450L
2021-02-22 08:03:13,406 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:03:13,440 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:03:13,440 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:03:13,445 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:03:13,445 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:03:13,446 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:03:13,446 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:03:13,446 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:03:13,446 DEBUG - Compression agreed: none
2021-02-22 08:03:13,468 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:03:13,469 DEBUG - Switch to new keys ...
2021-02-22 08:03:13,470 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:03:13,471 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:03:13,510 DEBUG - userauth is OK
2021-02-22 08:03:18,545 INFO - Authentication (publickey) failed.
2021-02-22 08:04:13,446 DEBUG - EOF in transport thread
2021-02-22 08:15:01,970 DEBUG - starting thread (client mode): 0xb932c090L
2021-02-22 08:15:01,970 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:15:02,005 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:15:02,005 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:15:02,010 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:15:02,011 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:15:02,011 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:15:02,011 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:15:02,011 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:15:02,011 DEBUG - Compression agreed: none
2021-02-22 08:15:02,034 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:15:02,034 DEBUG - Switch to new keys ...
2021-02-22 08:15:02,036 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:15:02,037 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:15:02,075 DEBUG - userauth is OK
2021-02-22 08:15:02,139 INFO - Authentication (publickey) failed.
2021-02-22 08:16:02,006 DEBUG - EOF in transport thread
2021-02-22 08:17:52,160 DEBUG - starting thread (client mode): 0xb96577d0L
2021-02-22 08:17:52,161 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:17:52,195 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:17:52,195 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:17:52,201 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:17:52,201 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:17:52,201 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:17:52,201 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:17:52,201 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:17:52,201 DEBUG - Compression agreed: none
2021-02-22 08:17:52,223 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:17:52,224 DEBUG - Switch to new keys ...
2021-02-22 08:17:52,226 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:17:52,227 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:17:52,265 DEBUG - userauth is OK
2021-02-22 08:17:52,330 INFO - Authentication (publickey) failed.
2021-02-22 08:18:52,195 DEBUG - EOF in transport thread
2021-02-22 08:33:13,430 DEBUG - starting thread (client mode): 0xb744d210L
2021-02-22 08:33:13,430 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:33:13,464 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:33:13,465 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:33:13,470 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:33:13,470 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:33:13,470 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:33:13,470 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:33:13,470 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:33:13,470 DEBUG - Compression agreed: none
2021-02-22 08:33:13,493 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:33:13,493 DEBUG - Switch to new keys ...
2021-02-22 08:33:13,496 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:33:13,497 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:33:13,534 DEBUG - userauth is OK
2021-02-22 08:33:13,601 INFO - Authentication (publickey) failed.
2021-02-22 08:34:13,467 DEBUG - EOF in transport thread
2021-02-22 10:07:39,644 ERROR - Internal Server Error: /esync/om-test_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-22 10:34:27,952 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 10:34:36,454 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 10:34:41,235 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 10:34:48,827 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 10:35:09,511 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 10:35:13,532 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 13:48:11,468 DEBUG - starting thread (client mode): 0xb73b5810L
2021-02-22 13:48:11,468 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 13:48:11,495 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 13:48:11,496 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 13:48:11,959 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 13:48:11,960 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 13:48:11,960 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 13:48:11,960 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 13:48:11,960 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 13:48:11,960 DEBUG - Compression agreed: none
2021-02-22 13:48:12,219 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 13:48:12,220 DEBUG - Switch to new keys ...
2021-02-22 13:48:12,238 DEBUG - Adding ssh-ed25519 host key for [106.13.216.53]:28032: a809e22e61ee19c3cded3d4b450df142
2021-02-22 13:48:12,239 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 13:48:12,300 DEBUG - userauth is OK
2021-02-22 13:48:14,347 INFO - Authentication (publickey) successful!
2021-02-22 13:48:14,355 DEBUG - EOF in transport thread
2021-02-22 13:48:18,387 DEBUG - starting thread (client mode): 0xb76f0250L
2021-02-22 13:48:18,387 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 13:48:18,659 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 13:48:18,660 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 13:48:18,661 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 13:48:18,661 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 13:48:18,661 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 13:48:18,661 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 13:48:18,661 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 13:48:18,661 DEBUG - Compression agreed: none
2021-02-22 13:48:18,747 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 13:48:18,747 DEBUG - Switch to new keys ...
2021-02-22 13:48:18,755 DEBUG - Adding ssh-ed25519 host key for [106.13.216.53]:28032: a809e22e61ee19c3cded3d4b450df142
2021-02-22 13:48:18,757 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 13:48:18,826 DEBUG - userauth is OK
2021-02-22 13:48:18,864 INFO - Authentication (publickey) successful!
2021-02-22 13:48:18,867 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-22 13:48:18,888 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-22 13:48:18,888 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-22 13:48:18,889 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-22 13:48:18,947 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-22 13:48:18,948 DEBUG - Secsh channel 0 opened.
2021-02-22 13:48:19,218 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-22 13:48:19,270 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-22 13:48:19,270 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-22 13:48:19,291 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-22 13:48:19,291 DEBUG - Secsh channel 1 opened.
2021-02-22 13:48:19,328 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-22 13:48:39,399 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-22 13:48:39,401 DEBUG - [chan 1] EOF received (1)
2021-02-22 13:48:39,401 DEBUG - [chan 1] EOF sent (1)
2021-02-22 13:48:39,421 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-22 13:48:39,421 DEBUG - Secsh channel 2 opened.
2021-02-22 13:48:39,504 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-22 13:48:39,516 DEBUG - [chan 2] EOF received (2)
2021-02-22 13:48:39,517 DEBUG - [chan 2] EOF sent (2)
2021-02-22 13:48:39,518 DEBUG - EOF in transport thread
2021-02-22 20:58:40,218 DEBUG - starting thread (client mode): 0xb6e23c90L
2021-02-22 20:58:40,218 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 20:58:40,257 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 20:58:40,257 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 20:58:40,266 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 20:58:40,266 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 20:58:40,267 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 20:58:40,267 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 20:58:40,267 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 20:58:40,267 DEBUG - Compression agreed: none
2021-02-22 20:58:40,289 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 20:58:40,290 DEBUG - Switch to new keys ...
2021-02-22 20:58:40,319 DEBUG - Adding ssh-ed25519 host key for [58.64.180.89]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 20:58:40,321 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 20:58:40,331 DEBUG - userauth is OK
2021-02-22 20:58:45,393 INFO - Authentication (publickey) successful!
2021-02-22 20:58:45,395 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-22 20:58:45,894 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-22 20:58:45,894 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-22 20:58:45,894 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-22 20:58:45,933 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-22 20:58:45,933 DEBUG - Secsh channel 0 opened.
2021-02-22 20:58:45,973 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-22 20:58:45,983 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-22 20:58:45,984 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-22 20:58:45,988 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-22 20:58:45,988 DEBUG - Secsh channel 1 opened.
2021-02-22 20:58:46,000 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-22 20:58:46,064 DEBUG - [chan 1] EOF received (1)
2021-02-22 20:58:46,064 DEBUG - EOF in transport thread
2021-02-22 20:58:46,067 DEBUG - [chan 1] EOF sent (1)
2021-02-22 20:58:46,067 DEBUG - Dropping user packet because connection is dead.
2021-02-22 20:58:46,072 DEBUG - starting thread (client mode): 0xb9641450L
2021-02-22 20:58:46,072 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 20:58:46,129 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 20:58:46,129 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 20:58:46,138 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 20:58:46,138 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 20:58:46,138 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 20:58:46,138 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 20:58:46,138 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 20:58:46,139 DEBUG - Compression agreed: none
2021-02-22 20:58:46,159 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 20:58:46,159 DEBUG - Switch to new keys ...
2021-02-22 20:58:46,173 DEBUG - Adding ssh-ed25519 host key for [58.64.180.89]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 20:58:46,174 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 20:58:46,200 DEBUG - userauth is OK
2021-02-22 20:58:51,264 INFO - Authentication (publickey) successful!
2021-02-22 20:58:51,272 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-22 20:58:51,468 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-22 20:58:51,468 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-22 20:58:51,469 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-22 20:58:51,508 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-22 20:58:51,508 DEBUG - Secsh channel 0 opened.
2021-02-22 20:58:51,547 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-22 20:58:51,558 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-22 20:58:51,559 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-22 20:58:51,560 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-22 20:58:51,560 DEBUG - Secsh channel 1 opened.
2021-02-22 20:58:51,572 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-22 20:58:51,601 DEBUG - [chan 1] EOF received (1)
2021-02-22 20:58:51,601 DEBUG - [chan 1] EOF sent (1)
2021-02-22 20:58:51,603 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-22 20:58:51,635 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-22 20:58:51,635 DEBUG - Secsh channel 2 opened.
2021-02-22 20:58:51,643 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-22 20:58:51,678 DEBUG - [chan 2] EOF received (2)
2021-02-22 20:58:51,678 DEBUG - [chan 2] EOF sent (2)
2021-02-22 20:58:51,679 DEBUG - [chan 3] Max packet in: 32768 bytes
2021-02-22 20:58:51,720 DEBUG - [chan 3] Max packet out: 32768 bytes
2021-02-22 20:58:51,720 DEBUG - Secsh channel 3 opened.
2021-02-22 20:58:51,750 DEBUG - [chan 3] Sesch channel 3 request ok
2021-02-22 20:58:51,796 DEBUG - [chan 3] EOF received (3)
2021-02-22 20:58:51,796 DEBUG - [chan 3] EOF sent (3)
2021-02-22 20:58:51,797 DEBUG - EOF in transport thread
2021-02-23 10:37:47,626 DEBUG - (terrytang) - Successfully loaded and updated table
2021-02-23 15:16:10,668 ERROR - Internal Server Error: /fwdcontrol/test-public-nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/fwdcontrol/views.py", line 46, in get
    context['content'] = result.get()
  File "/app/argus_final/venv/lib/python2.7/site-packages/celery/result.py", line 224, in get
    on_message=on_message,
  File "/app/argus_final/venv/lib/python2.7/site-packages/celery/backends/async.py", line 190, in wait_for_pending
    return result.maybe_throw(callback=callback, propagate=propagate)
  File "/app/argus_final/venv/lib/python2.7/site-packages/celery/result.py", line 329, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/app/argus_final/venv/lib/python2.7/site-packages/celery/result.py", line 322, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/vine/promises.py", line 217, in throw
    reraise(type(exc), exc, tb)
  File "<string>", line 1, in reraise
IOError: (u'[', u'E', u'r', u'r', u'n', u'o', u' ', u'2', u'1', u']', u' ', u'I', u's', u' ', u'a', u' ', u'd', u'i', u'r', u'e', u'c', u't', u'o', u'r', u'y', u':', u' ', u'u', u"'", u'/', u's', u'r', u'v', u'/', u't', u'e', u's', u't', u'-', u'p', u'u', u'b', u'l', u'i', u'c', u'-', u'n', u'g', u'i', u'n', u'x', u'/', u'c', u'o', u'n', u'f', u'.', u'd', u'/', u's', u's', u'l', u"'")
2021-02-23 17:51:42,517 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-23 17:57:19,822 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
2021-02-23 18:01:35,636 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 207-208: ordinal not in range(128)
2021-02-23 18:01:58,293 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 207-208: ordinal not in range(128)
2021-02-23 18:16:28,379 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 258-259: ordinal not in range(128)
2021-02-23 18:17:16,983 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 306-307: ordinal not in range(128)
2021-02-23 18:19:05,769 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 352-353: ordinal not in range(128)
2021-02-24 01:11:50,776 DEBUG - starting thread (client mode): 0xb761bb50L
2021-02-24 01:11:50,776 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-24 01:11:50,791 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-24 01:11:50,791 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-24 01:11:50,794 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-24 01:11:50,794 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-24 01:11:50,794 DEBUG - HostKey agreed: ssh-ed25519
2021-02-24 01:11:50,794 DEBUG - Cipher agreed: aes128-ctr
2021-02-24 01:11:50,794 DEBUG - MAC agreed: hmac-sha2-256
2021-02-24 01:11:50,795 DEBUG - Compression agreed: none
2021-02-24 01:11:50,804 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-24 01:11:50,805 DEBUG - Switch to new keys ...
2021-02-24 01:11:50,809 DEBUG - Adding ssh-ed25519 host key for [58.64.167.40]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-24 01:11:50,811 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-24 01:11:50,845 DEBUG - userauth is OK
2021-02-24 01:11:55,874 INFO - Authentication (publickey) successful!
2021-02-24 01:11:55,880 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-24 01:11:55,892 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-24 01:11:55,892 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-24 01:11:55,892 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-24 01:11:55,932 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-24 01:11:55,932 DEBUG - Secsh channel 0 opened.
2021-02-24 01:11:55,949 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 01:11:55,953 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 01:11:55,954 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-24 01:11:55,955 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-24 01:11:55,955 DEBUG - Secsh channel 1 opened.
2021-02-24 01:11:55,962 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-24 01:12:06,441 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-24 01:12:06,443 DEBUG - [chan 1] EOF received (1)
2021-02-24 01:12:06,443 DEBUG - [chan 1] EOF sent (1)
2021-02-24 01:12:06,444 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-24 01:12:06,444 DEBUG - Secsh channel 2 opened.
2021-02-24 01:12:06,497 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-24 01:12:06,524 DEBUG - [chan 2] EOF received (2)
2021-02-24 01:12:06,525 DEBUG - [chan 2] EOF sent (2)
2021-02-24 01:12:06,526 DEBUG - EOF in transport thread
2021-02-24 07:56:39,802 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 08:02:05,917 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 08:02:10,478 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 08:09:55,476 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 08:10:21,710 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 08:46:14,994 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:07:20,321 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:07:23,741 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:09:20,351 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 306-307: ordinal not in range(128)
2021-02-24 09:12:46,018 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:13:20,402 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:13:23,049 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:13:30,948 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:13:44,071 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:14:01,221 DEBUG - starting thread (client mode): 0xb74ab2d0L
2021-02-24 09:14:01,221 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-24 09:14:01,352 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-02-24 09:14:01,352 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-02-24 09:14:01,360 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-24 09:14:01,360 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-02-24 09:14:01,361 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-02-24 09:14:01,361 DEBUG - Cipher agreed: aes128-ctr
2021-02-24 09:14:01,361 DEBUG - MAC agreed: hmac-sha2-256
2021-02-24 09:14:01,361 DEBUG - Compression agreed: none
2021-02-24 09:14:01,380 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-02-24 09:14:01,380 DEBUG - Switch to new keys ...
2021-02-24 09:14:01,388 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.19.167]:28032: 75d1c31170d6257e2001c1129928c81c
2021-02-24 09:14:01,390 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-24 09:14:01,440 DEBUG - userauth is OK
2021-02-24 09:14:06,580 INFO - Authentication (publickey) successful!
2021-02-24 09:14:06,593 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-24 09:14:07,148 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-24 09:14:07,196 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-24 09:14:07,197 DEBUG - Secsh channel 0 opened.
2021-02-24 09:14:07,217 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 09:14:07,225 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 09:14:07,226 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-24 09:14:07,232 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-24 09:14:07,233 DEBUG - Secsh channel 1 opened.
2021-02-24 09:14:07,251 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-24 09:14:24,250 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-24 09:14:24,252 DEBUG - [chan 1] EOF received (1)
2021-02-24 09:14:24,253 DEBUG - [chan 1] EOF sent (1)
2021-02-24 09:14:24,257 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-24 09:14:24,258 DEBUG - Secsh channel 2 opened.
2021-02-24 09:14:24,308 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-24 09:14:24,518 DEBUG - [chan 2] EOF received (2)
2021-02-24 09:14:24,518 DEBUG - [chan 2] EOF sent (2)
2021-02-24 09:14:24,519 DEBUG - EOF in transport thread
2021-02-24 09:55:08,612 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 211-212: ordinal not in range(128)
2021-02-24 10:10:34,179 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 10:10:46,152 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 10:10:47,268 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 11:04:38,107 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 13:28:01,196 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 14:02:30,792 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 15:17:30,006 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-24 15:17:35,544 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-24 15:20:25,511 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-24 15:34:14,035 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-25 10:57:44,213 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 308-309: ordinal not in range(128)
2021-02-25 16:15:34,296 DEBUG - (jerry.lam) - Successfully loaded and updated table
2021-02-25 16:16:41,325 DEBUG - (jerry.lam) - Successfully loaded and updated table
2021-02-25 16:36:09,254 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-26 16:13:38,772 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 268-271: ordinal not in range(128)
