2020-10-09 08:10:23,849 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:15:32,555 DEBUG - (jonas.nicanor) - Successfully loaded and updated table
2020-10-09 08:21:01,985 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:21:23,572 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:21:29,333 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:21:44,048 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:22:42,679 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:22:58,006 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:23:06,142 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:23:15,539 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:23:32,287 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:28:30,629 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:29:04,486 DEBUG - (james.cadelina) - Successfully loaded and updated table
2020-10-09 08:46:25,962 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2020-10-09 08:48:07,838 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2020-10-09 09:11:48,943 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:12:49,040 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 40, in get
    context['data'] = ZABBIX.getAllEvents(daysfromnow=period)[-limit:]
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 121, in getAllEvents
    events = self.zapi.do_request('event.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:14:19,325 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:15:19,397 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 40, in get
    context['data'] = ZABBIX.getAllEvents(daysfromnow=period)[-limit:]
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 121, in getAllEvents
    events = self.zapi.do_request('event.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:16:50,322 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:17:50,397 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 40, in get
    context['data'] = ZABBIX.getAllEvents(daysfromnow=period)[-limit:]
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 121, in getAllEvents
    events = self.zapi.do_request('event.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:19:21,318 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:20:21,387 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 40, in get
    context['data'] = ZABBIX.getAllEvents(daysfromnow=period)[-limit:]
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 121, in getAllEvents
    events = self.zapi.do_request('event.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:20:40,979 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:21:41,065 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 40, in get
    context['data'] = ZABBIX.getAllEvents(daysfromnow=period)[-limit:]
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 121, in getAllEvents
    events = self.zapi.do_request('event.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:21:52,322 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 30, in get
    context['data'] = ZABBIX.getAllTriggeredTriggers()
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 80, in getAllTriggeredTriggers
    triggers = self.zapi.do_request('trigger.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:22:52,391 ERROR - Internal Server Error: /monitoring/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/monitoring/views.py", line 40, in get
    context['data'] = ZABBIX.getAllEvents(daysfromnow=period)[-limit:]
  File "/app/argus_final/app/argus/global_objects/zabbix_api.py", line 121, in getAllEvents
    events = self.zapi.do_request('event.get',req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 251, in do_request
    res = urlopen(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 117, in inner
    res = func(req)
  File "/app/argus_final/venv/lib/python2.7/site-packages/pyzabbix/api.py", line 126, in urlopen
    return urllib2.urlopen(*args, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out
2020-10-09 09:30:17,814 DEBUG - (rock.lim) - Successfully loaded and updated table
2020-10-09 12:11:46,905 DEBUG - (rock.lim) - Successfully loaded and updated table
2020-10-09 14:21:03,227 ERROR - Internal Server Error: /esync/om-cdn_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
