2021-02-22 08:06:48,213 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 08:11:25,892 DEBUG - starting thread (client mode): 0xb9d92b50L
2021-02-22 08:11:25,892 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:11:25,930 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:11:25,930 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:11:25,934 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:11:25,934 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:11:25,934 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:11:25,934 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:11:25,934 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:11:25,934 DEBUG - Compression agreed: none
2021-02-22 08:11:25,957 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:11:25,958 DEBUG - Switch to new keys ...
2021-02-22 08:11:25,960 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:11:25,961 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:11:25,999 DEBUG - userauth is OK
2021-02-22 08:11:26,059 INFO - Authentication (publickey) failed.
2021-02-22 08:11:42,507 DEBUG - starting thread (client mode): 0xb95be450L
2021-02-22 08:11:42,507 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:11:42,541 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:11:42,541 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:11:42,547 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:11:42,547 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:11:42,547 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:11:42,547 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:11:42,547 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:11:42,547 DEBUG - Compression agreed: none
2021-02-22 08:11:42,570 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:11:42,571 DEBUG - Switch to new keys ...
2021-02-22 08:11:42,573 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:11:42,574 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:11:42,611 DEBUG - userauth is OK
2021-02-22 08:11:42,671 INFO - Authentication (publickey) failed.
2021-02-22 08:12:25,937 DEBUG - EOF in transport thread
2021-02-22 08:12:42,542 DEBUG - EOF in transport thread
2021-02-22 08:14:28,570 DEBUG - starting thread (client mode): 0xb99d4b50L
2021-02-22 08:14:28,570 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:14:28,611 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:14:28,611 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:14:28,617 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:14:28,617 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:14:28,617 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:14:28,617 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:14:28,617 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:14:28,617 DEBUG - Compression agreed: none
2021-02-22 08:14:28,640 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:14:28,641 DEBUG - Switch to new keys ...
2021-02-22 08:14:28,671 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:14:28,672 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:14:28,681 DEBUG - userauth is OK
2021-02-22 08:14:28,745 INFO - Authentication (publickey) failed.
2021-02-22 08:15:28,612 DEBUG - EOF in transport thread
2021-02-22 08:18:08,714 DEBUG - starting thread (client mode): 0xb9b32a50L
2021-02-22 08:18:08,714 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:18:08,749 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:18:08,750 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:18:08,755 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:18:08,755 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:18:08,755 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:18:08,755 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:18:08,755 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:18:08,756 DEBUG - Compression agreed: none
2021-02-22 08:18:08,778 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:18:08,779 DEBUG - Switch to new keys ...
2021-02-22 08:18:08,781 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:18:08,782 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:18:08,820 DEBUG - userauth is OK
2021-02-22 08:18:08,886 INFO - Authentication (publickey) failed.
2021-02-22 08:19:08,750 DEBUG - EOF in transport thread
2021-02-22 08:27:38,416 DEBUG - starting thread (client mode): 0xb95d1b50L
2021-02-22 08:27:38,417 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:27:38,450 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:27:38,450 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:27:38,456 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:27:38,456 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:27:38,456 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:27:38,456 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:27:38,457 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:27:38,457 DEBUG - Compression agreed: none
2021-02-22 08:27:38,479 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:27:38,479 DEBUG - Switch to new keys ...
2021-02-22 08:27:38,482 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:27:38,483 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:27:38,520 DEBUG - userauth is OK
2021-02-22 08:27:38,581 INFO - Authentication (publickey) failed.
2021-02-22 08:28:38,455 DEBUG - EOF in transport thread
2021-02-22 08:33:42,565 DEBUG - starting thread (client mode): 0xb963c890L
2021-02-22 08:33:42,565 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 08:33:42,600 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 08:33:42,600 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 08:33:42,606 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 08:33:42,606 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 08:33:42,606 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 08:33:42,606 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 08:33:42,606 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 08:33:42,606 DEBUG - Compression agreed: none
2021-02-22 08:33:42,629 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 08:33:42,629 DEBUG - Switch to new keys ...
2021-02-22 08:33:42,631 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 08:33:42,632 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 08:33:42,671 DEBUG - userauth is OK
2021-02-22 08:33:42,733 INFO - Authentication (publickey) failed.
2021-02-22 08:34:42,603 DEBUG - EOF in transport thread
2021-02-22 09:56:08,124 ERROR - Internal Server Error: /esync/om-test_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-22 10:34:07,937 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 10:34:19,944 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-02-22 20:56:49,808 DEBUG - starting thread (client mode): 0xb9ce8350L
2021-02-22 20:56:49,808 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-22 20:56:49,854 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-22 20:56:49,855 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-22 20:56:49,865 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-22 20:56:49,865 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-22 20:56:49,866 DEBUG - HostKey agreed: ssh-ed25519
2021-02-22 20:56:49,866 DEBUG - Cipher agreed: aes128-ctr
2021-02-22 20:56:49,866 DEBUG - MAC agreed: hmac-sha2-256
2021-02-22 20:56:49,866 DEBUG - Compression agreed: none
2021-02-22 20:56:49,886 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-22 20:56:49,887 DEBUG - Switch to new keys ...
2021-02-22 20:56:49,910 DEBUG - Adding ssh-ed25519 host key for [58.64.180.89]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-22 20:56:49,911 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-22 20:56:49,928 DEBUG - userauth is OK
2021-02-22 20:56:54,991 INFO - Authentication (publickey) successful!
2021-02-22 20:56:55,012 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-22 20:56:55,504 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-22 20:56:55,504 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-22 20:56:55,504 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-22 20:56:55,544 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-22 20:56:55,545 DEBUG - Secsh channel 0 opened.
2021-02-22 20:56:55,557 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-22 20:56:55,565 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-22 20:56:55,565 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-22 20:56:55,568 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-22 20:56:55,568 DEBUG - Secsh channel 1 opened.
2021-02-22 20:56:55,580 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-22 20:57:08,658 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-22 20:57:08,660 DEBUG - [chan 1] EOF received (1)
2021-02-22 20:57:08,660 DEBUG - [chan 1] EOF sent (1)
2021-02-22 20:57:08,661 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-22 20:57:08,661 DEBUG - Secsh channel 2 opened.
2021-02-22 20:57:08,711 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-22 20:57:08,762 DEBUG - [chan 2] EOF received (2)
2021-02-22 20:57:08,762 DEBUG - [chan 2] EOF sent (2)
2021-02-22 20:57:08,763 DEBUG - EOF in transport thread
2021-02-23 10:37:54,759 DEBUG - (terrytang) - Successfully loaded and updated table
2021-02-23 16:15:52,915 DEBUG - starting thread (client mode): 0xb9141190L
2021-02-23 16:15:52,915 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-23 16:15:53,174 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-23 16:15:53,175 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-23 16:15:53,181 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-23 16:15:53,181 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-23 16:15:53,181 DEBUG - HostKey agreed: ssh-ed25519
2021-02-23 16:15:53,181 DEBUG - Cipher agreed: aes128-ctr
2021-02-23 16:15:53,181 DEBUG - MAC agreed: hmac-sha2-256
2021-02-23 16:15:53,182 DEBUG - Compression agreed: none
2021-02-23 16:15:53,203 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-23 16:15:53,204 DEBUG - Switch to new keys ...
2021-02-23 16:15:53,218 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-23 16:15:53,219 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-23 16:15:53,245 DEBUG - userauth is OK
2021-02-23 16:15:58,409 INFO - Authentication (publickey) failed.
2021-02-23 16:16:53,177 DEBUG - EOF in transport thread
2021-02-23 18:03:48,567 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 207-208: ordinal not in range(128)
2021-02-23 18:15:22,187 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 244-247: ordinal not in range(128)
2021-02-24 01:03:22,905 DEBUG - starting thread (client mode): 0xb88c5690L
2021-02-24 01:03:22,906 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-24 01:03:22,925 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-24 01:03:22,925 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-24 01:03:22,930 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-24 01:03:22,930 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-24 01:03:22,930 DEBUG - HostKey agreed: ssh-ed25519
2021-02-24 01:03:22,931 DEBUG - Cipher agreed: aes128-ctr
2021-02-24 01:03:22,931 DEBUG - MAC agreed: hmac-sha2-256
2021-02-24 01:03:22,931 DEBUG - Compression agreed: none
2021-02-24 01:03:22,988 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-24 01:03:22,989 DEBUG - Switch to new keys ...
2021-02-24 01:03:23,006 DEBUG - Adding ssh-ed25519 host key for [103.40.8.28]:28032: ea76ce94b93e3e0b925af7530a54fa6f
2021-02-24 01:03:23,008 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-24 01:03:23,040 DEBUG - userauth is OK
2021-02-24 01:03:28,079 INFO - Authentication (publickey) successful!
2021-02-24 01:03:28,111 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-24 01:03:28,116 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-24 01:03:28,117 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-24 01:03:28,117 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-24 01:03:28,161 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-24 01:03:28,161 DEBUG - Secsh channel 0 opened.
2021-02-24 01:03:28,184 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 01:03:28,194 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 01:03:28,195 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-24 01:03:28,200 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-24 01:03:28,200 DEBUG - Secsh channel 1 opened.
2021-02-24 01:03:28,210 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-24 01:03:38,967 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-24 01:03:38,969 DEBUG - [chan 1] EOF received (1)
2021-02-24 01:03:38,970 DEBUG - [chan 1] EOF sent (1)
2021-02-24 01:03:38,974 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-24 01:03:38,974 DEBUG - Secsh channel 2 opened.
2021-02-24 01:03:39,026 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-24 01:03:39,047 DEBUG - [chan 2] EOF received (2)
2021-02-24 01:03:39,048 DEBUG - [chan 2] EOF sent (2)
2021-02-24 01:03:39,049 DEBUG - EOF in transport thread
2021-02-24 01:49:17,685 DEBUG - starting thread (client mode): 0xb916ac90L
2021-02-24 01:49:17,685 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-24 01:49:17,700 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-24 01:49:17,700 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-24 01:49:17,702 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-24 01:49:17,702 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-24 01:49:17,702 DEBUG - HostKey agreed: ssh-ed25519
2021-02-24 01:49:17,702 DEBUG - Cipher agreed: aes128-ctr
2021-02-24 01:49:17,703 DEBUG - MAC agreed: hmac-sha2-256
2021-02-24 01:49:17,703 DEBUG - Compression agreed: none
2021-02-24 01:49:17,712 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-24 01:49:17,713 DEBUG - Switch to new keys ...
2021-02-24 01:49:17,719 DEBUG - Adding ssh-ed25519 host key for [58.64.167.40]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-24 01:49:17,720 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-24 01:49:17,753 DEBUG - userauth is OK
2021-02-24 01:49:17,808 INFO - Authentication (publickey) successful!
2021-02-24 01:49:17,821 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-24 01:49:17,822 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-24 01:49:17,823 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-24 01:49:17,823 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-24 01:49:17,863 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-24 01:49:17,864 DEBUG - Secsh channel 0 opened.
2021-02-24 01:49:17,891 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 01:49:17,895 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 01:49:17,896 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-24 01:49:17,897 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-24 01:49:17,898 DEBUG - Secsh channel 1 opened.
2021-02-24 01:49:17,902 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-24 01:49:17,930 DEBUG - [chan 1] EOF received (1)
2021-02-24 01:49:17,930 DEBUG - [chan 1] EOF sent (1)
2021-02-24 01:49:17,931 DEBUG - EOF in transport thread
2021-02-24 01:49:17,939 DEBUG - starting thread (client mode): 0xb98269d0L
2021-02-24 01:49:17,939 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-02-24 01:49:17,956 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-02-24 01:49:17,956 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-02-24 01:49:17,959 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-02-24 01:49:17,959 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-02-24 01:49:17,959 DEBUG - HostKey agreed: ssh-ed25519
2021-02-24 01:49:17,959 DEBUG - Cipher agreed: aes128-ctr
2021-02-24 01:49:17,959 DEBUG - MAC agreed: hmac-sha2-256
2021-02-24 01:49:17,960 DEBUG - Compression agreed: none
2021-02-24 01:49:17,969 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-02-24 01:49:17,969 DEBUG - Switch to new keys ...
2021-02-24 01:49:17,972 DEBUG - Adding ssh-ed25519 host key for [58.64.167.40]:28032: 649bfb2ade50b259183468bcc4a641be
2021-02-24 01:49:17,973 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-02-24 01:49:18,010 DEBUG - userauth is OK
2021-02-24 01:49:18,067 INFO - Authentication (publickey) successful!
2021-02-24 01:49:18,074 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-02-24 01:49:18,080 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-02-24 01:49:18,080 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-02-24 01:49:18,080 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-02-24 01:49:18,120 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-02-24 01:49:18,120 DEBUG - Secsh channel 0 opened.
2021-02-24 01:49:18,141 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 01:49:18,145 DEBUG - [chan 0] Sesch channel 0 request ok
2021-02-24 01:49:18,146 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-02-24 01:49:18,147 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-02-24 01:49:18,147 DEBUG - Secsh channel 1 opened.
2021-02-24 01:49:18,155 DEBUG - [chan 1] Sesch channel 1 request ok
2021-02-24 01:49:18,181 DEBUG - [chan 1] EOF received (1)
2021-02-24 01:49:18,181 DEBUG - [chan 1] EOF sent (1)
2021-02-24 01:49:18,182 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-02-24 01:49:18,192 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-02-24 01:49:18,192 DEBUG - Secsh channel 2 opened.
2021-02-24 01:49:18,202 DEBUG - [chan 2] Sesch channel 2 request ok
2021-02-24 01:49:18,228 DEBUG - [chan 2] EOF received (2)
2021-02-24 01:49:18,228 DEBUG - [chan 2] EOF sent (2)
2021-02-24 01:49:18,230 DEBUG - [chan 3] Max packet in: 32768 bytes
2021-02-24 01:49:18,270 DEBUG - [chan 3] Max packet out: 32768 bytes
2021-02-24 01:49:18,270 DEBUG - Secsh channel 3 opened.
2021-02-24 01:49:18,299 DEBUG - [chan 3] Sesch channel 3 request ok
2021-02-24 01:49:18,382 DEBUG - [chan 3] EOF received (3)
2021-02-24 01:49:18,383 DEBUG - [chan 3] EOF sent (3)
2021-02-24 01:49:18,384 DEBUG - EOF in transport thread
2021-02-24 07:14:13,946 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 07:17:04,587 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 210-211: ordinal not in range(128)
2021-02-24 08:02:02,728 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 08:09:45,772 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:04:35,000 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 520-521: ordinal not in range(128)
2021-02-24 09:06:58,730 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:08:47,122 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 306-307: ordinal not in range(128)
2021-02-24 09:12:44,066 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 09:14:21,359 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 301-302: ordinal not in range(128)
2021-02-24 09:53:19,006 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 10:09:37,376 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 10:10:36,764 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 10:18:31,724 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 10:59:12,910 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 457-458: ordinal not in range(128)
2021-02-24 11:05:18,419 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 321-322: ordinal not in range(128)
2021-02-24 13:46:06,095 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 13:46:35,635 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 306-307: ordinal not in range(128)
2021-02-24 14:02:15,797 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-24 14:23:55,197 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-24 14:30:56,086 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-24 15:17:41,937 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-24 15:20:17,562 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-24 15:20:42,990 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-24 15:33:47,758 DEBUG - (alexeio) - Successfully loaded and updated table
2021-02-25 10:57:07,732 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 11:09:36,004 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 11:09:54,750 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 307-308: ordinal not in range(128)
2021-02-25 12:06:19,012 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:25:36,919 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:35:57,069 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:35:59,073 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:36:07,166 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:36:21,183 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:36:42,970 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:36:44,726 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:36:55,804 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-02-25 16:37:31,777 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 305-306: ordinal not in range(128)
2021-02-26 10:50:58,489 ERROR - Internal Server Error: /puppet/om-newlive800_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/puppet/views.py", line 177, in post
    nonstandard_puppet_log(hostgroup, request.user.username, [result[1]], activity_type='CREATE')
  File "/app/argus_final/app/argus/puppet/lib/puppet_logger.py", line 20, in nonstandard_puppet_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 178-181: ordinal not in range(128)
2021-02-26 13:58:31,992 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 313-314: ordinal not in range(128)
2021-02-26 14:13:15,424 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 316-317: ordinal not in range(128)
2021-02-26 14:13:48,868 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 316-317: ordinal not in range(128)
