PUPPET_COMMAND_END
MAX RETRIES EXECUTED, COMMAND NOT RESPONDINGPUPPET_COMMAND_START

PLAY [puppetmaster] ************************************************************

TASK [puppetmaster : stat] *****************************************************
ok: [119.81.239.189 -> localhost]


TASK [puppetmaster : debug] ****************************************************
skipping: [119.81.239.189]

TASK [puppetmaster : stat] *****************************************************

skipping: [119.81.239.189]

TASK [puppetmaster : debug] ****************************************************
skipping: [119.81.239.189]


TASK [puppetmaster : stat] *****************************************************
skipping: [119.81.239.189]

TASK [puppetmaster : debug] ****************************************************
skipping: [119.81.239.189]


TASK [puppetmaster : stat] *****************************************************
skipping: [119.81.239.189]

TASK [puppetmaster : debug] ****************************************************

skipping: [119.81.239.189]

TASK [puppetmaster : set_fact] *************************************************
ok: [119.81.239.189]


TASK [puppetmaster : include_tasks] ********************************************
included: /ansible/puppet/roles/puppetmaster/tasks/puppetcreate.yml for 119.81.239.189

TASK [puppetmaster : Create sub directory] *************************************
failed: [119.81.239.189] (item=modules) => {"changed": false, "item": "modules", "module_stderr": "Warning: Permanently added '[119.81.239.189]:2556' (RSA) to the list of known hosts.\r\nTraceback (most recent call last):\n  File \"<stdin>\", line 112, in <module>\n  File \"/usr/lib64/python2.6/tempfile.py\", line 310, in mkdtemp\n    dir = gettempdir()\n  File \"/usr/lib64/python2.6/tempfile.py\", line 254, in gettempdir\n    tempdir = _get_default_tempdir()\n  File \"/usr/lib64/python2.6/tempfile.py\", line 201, in _get_default_tempdir\n    (\"No usable temporary directory found in %s\" % dirlist))\nIOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/root']\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

failed: [119.81.239.189] (item=manifests) => {"changed": false, "item": "manifests", "module_stderr": "Warning: Permanently added '[119.81.239.189]:2556' (RSA) to the list of known hosts.\r\nTraceback (most recent call last):\n  File \"<stdin>\", line 112, in <module>\n  File \"/usr/lib64/python2.6/tempfile.py\", line 310, in mkdtemp\n    dir = gettempdir()\n  File \"/usr/lib64/python2.6/tempfile.py\", line 254, in gettempdir\n    tempdir = _get_default_tempdir()\n  File \"/usr/lib64/python2.6/tempfile.py\", line 201, in _get_default_tempdir\n    (\"No usable temporary directory found in %s\" % dirlist))\nIOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/root']\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/ansible/puppet/site.retry

PLAY RECAP *********************************************************************
119.81.239.189             : ok=3    changed=0    unreachable=0    failed=1   



